Fix `just check-full` CI failure
Adding openapi3/servant-openapi3 mysteriously caused the following
error on windows cross-build:

    error: The option `packages."Cabal-3.12.1.0-inplace".package.license' was accessed
    but has no value defined. Try setting the option.

This was caused by the "custom-setup" carried over by the packages
above. Since we don't care about doctests, we brute-force a "simple"
cabal build